name: hero_market
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  go_router: ^14.6.1
  get_it: ^8.0.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  provider: ^6.1.2
  gap: ^3.0.1
  country_picker: ^2.0.27
  flutter_multi_formatter: ^2.13.0
  pin_code_fields: ^8.0.1
  curved_navigation_bar: ^1.0.6
  iconly: ^1.0.1
  collection: ^1.19.0
  webview_flutter: ^4.10.0
  flutter_native_splash: ^2.4.4
  iconify_flutter: ^0.0.7
  lottie: ^3.3.1
  infinite_scroll_pagination: ^4.0.0
  carousel_slider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

    
  fonts:
    - family: Switzer
      fonts:
        - asset: assets/fonts/Switzer-Black.otf
        - asset: assets/fonts/Switzer-BlackItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Bold.otf
        - asset: assets/fonts/Switzer-BoldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Extrabold.otf
        - asset: assets/fonts/Switzer-ExtraboldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Extralight.otf
        - asset: assets/fonts/Switzer-ExtralightItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Italic.otf
          style: italic
        - asset: assets/fonts/Switzer-Light.otf
        - asset: assets/fonts/Switzer-LightItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Medium.otf
        - asset: assets/fonts/Switzer-MediumItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Regular.otf
        - asset: assets/fonts/Switzer-Semibold.otf
        - asset: assets/fonts/Switzer-SemiboldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Thin.otf
        - asset: assets/fonts/Switzer-ThinItalic.otf
          style: italic
